### ISSUE TITLE
Add this to nuget?

### ISSUE THREAD

**Issue by Krutonium** [Indieteur/GlobalHooks#1]
Also, if I may suggest, even though it's not required, putting the license text in a LICENSE.MD file?

**Comment by Indieteur** [comment]
I'll try doing that this upcoming week 👍

**Comment by Indieteur** [comment]
I added a license.md by the way. As for the nuget package, I'll be working on that next week.

**Comment by Krutonium** [comment]
👍 Thanks Man!

**Comment by Indieteur** [comment]
Created a Nuget package and submitted it to Nuget.org for review. I'll let you know once it is up!

**EDIT: It's already up. Didn't expect it to be quick. Package name is Indieteur.GlobalHooks**
