### ISSUE TITLE
Unable to get output.

### ISSUE THREAD

**Issue by Krutonium** [Indieteur/GlobalHooks#3]
I have a problem, and I'm not sure if it's my fault or yours. With the following Code, in a console application, I don't get any output printed to the console (nor are breakpoints in the events hit), and system wide text input becomes incredibly slow, up to 3/4 of a second per character.

```
    class Program
    {
        static GlobalKeyHook globalKeyHook;
        static void Main(string[] args)
        {
            globalKeyHook = new GlobalKeyHook();
            globalKeyHook.OnKeyDown += GlobalKeyHook_OnKeyDown;
            globalKeyHook.OnKeyPressed += GlobalKeyHook_OnKeyPressed;
            globalKeyHook.OnKeyUp += GlobalKeyHook_OnKeyUp;
            Console.ReadKey();
        }

        private static void GlobalKeyHook_OnKeyUp(object sender, GlobalKeyEventArgs e)
        {
            Console.WriteLine("Released" + e.CharResult);
        }

        private static void GlobalKeyHook_OnKeyPressed(object sender, GlobalKeyEventArgs e)
        {
            Console.WriteLine("Pressed " + e.CharResult);
        }

        private static void GlobalKeyHook_OnKeyDown(object sender, GlobalKeyEventArgs e)
        {
            Console.WriteLine("KeyDown " + e.CharResult);
        }
    }
```

Am I doing something wrong, or is the bug elsewhere?

**Comment by Indieteur** [comment]
It should be working so I'll be checking on this soon! Sorry for the late reply. :) 

EDIT: I'll work on this next week and see what's wrong. I'm currently busy right now with other things.

**Comment by Krutonium** [comment]
👍

**Comment by Indieteur** [comment]
I haven't looked into the issue yet but I'll check on it tomorrow. But before that, have you tried checking if the event itself is actually being called when you press a key? This would help me a lot with the investigation.

**Comment by Indieteur** [comment]
Hi. I believe I've found the solution for your issue. See Console Test project for more details. 👍
